[2024-06-11 06:39:29,293] [APPLOG] [INFO] : add address| Manager Function Started
[2024-06-11 06:39:29,374] [APPLOG] [INFO] : ADDRESS | API executed Successfully
[2024-06-11 06:42:22,741] [APPLOG] [INFO] : add address| Manager Function Started
[2024-06-11 06:42:42,761] [APPLOG] [ERROR] : ADDRESS | Api execution Failed with 500 status code 
[2024-06-11 06:43:00,803] [APPLOG] [INFO] : add address| Manager Function Started
[2024-06-11 06:43:46,575] [APPLOG] [ERROR] : ADDRESS | Api execution Failed with 500 status code 
[2024-06-11 06:44:08,562] [APPLOG] [INFO] : add address| Manager Function Started
[2024-06-11 06:44:16,673] [APPLOG] [INFO] : ADDRESS UPDATE | API executed Successfully
[2024-06-11 06:58:20,338] [APPLOG] [ERROR] : ADDRESS GET |Exception occured in listing verticals  : 
Traceback (most recent call last):
  File "C:\Users\Roshan Mechoth\Documents\address_book\address_book\routers\address.py", line 76, in get_address_by_id
    res = get_manager(id)
TypeError: get_manager() missing 1 required positional argument: 'id'

[2024-06-11 06:59:16,070] [APPLOG] [INFO] : add address| Manager Function Started
[2024-06-11 06:59:45,395] [APPLOG] [INFO] : ADDRESS GET | API executed Successfully
[2024-06-11 07:00:18,462] [APPLOG] [INFO] : add address| Manager Function Started
[2024-06-11 07:00:18,490] [APPLOG] [INFO] : ADDRESS GET | API executed Successfully
[2024-06-11 07:00:21,996] [APPLOG] [INFO] : add address| Manager Function Started
[2024-06-11 07:00:22,002] [APPLOG] [INFO] : ADDRESS GET | API executed Successfully
[2024-06-11 07:00:26,522] [APPLOG] [INFO] : add address| Manager Function Started
[2024-06-11 07:00:26,530] [APPLOG] [INFO] : ADDRESS GET | API executed Successfully
[2024-06-11 07:15:47,812] [APPLOG] [INFO] : add address| Manager Function Started
[2024-06-11 07:16:04,633] [APPLOG] [INFO] : ADDRESS DELETE | API executed Successfully
[2024-06-11 07:33:28,589] [APPLOG] [INFO] : add address| Manager Function Started
[2024-06-11 07:33:28,655] [APPLOG] [INFO] : ADDRESS | API executed Successfully
[2024-06-11 07:35:11,049] [APPLOG] [INFO] : add address| Manager Function Started
[2024-06-11 07:36:08,562] [APPLOG] [INFO] : retrieve_addresses  | API executed Successfully
[2024-06-11 07:36:09,098] [APPLOG] [ERROR] : retrieve_addresses |Exception occured in listing verticals  : 
Traceback (most recent call last):
  File "C:\Users\Roshan Mechoth\Documents\address_book\address_book\routers\address.py", line 133, in get_address_by_data
    return JSONResponse(status_code=res['code'],
  File "C:\Users\Roshan Mechoth\Documents\address_book\env\address_book\lib\site-packages\starlette\responses.py", line 196, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\Roshan Mechoth\Documents\address_book\env\address_book\lib\site-packages\starlette\responses.py", line 55, in __init__
    self.body = self.render(content)
  File "C:\Users\Roshan Mechoth\Documents\address_book\env\address_book\lib\site-packages\starlette\responses.py", line 199, in render
    return json.dumps(
  File "C:\Program Files\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Program Files\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Address is not JSON serializable

[2024-06-11 07:36:18,876] [APPLOG] [INFO] : add address| Manager Function Started
[2024-06-11 07:36:44,725] [APPLOG] [INFO] : retrieve_addresses  | API executed Successfully
[2024-06-11 07:39:40,878] [APPLOG] [INFO] : add address| Manager Function Started
[2024-06-11 07:39:41,445] [APPLOG] [INFO] : retrieve_addresses  | API executed Successfully
